<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250721204621 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE clients (first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, middle_name VARCHAR(255) DEFAULT NULL, income INT NOT NULL, age INT NOT NULL, pin VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, score INT NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(50) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE loans (name VARCHAR(255) NOT NULL, amount INT NOT NULL, rate DOUBLE PRECISION NOT NULL, term INT NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_82C24DBC19EB6921 ON loans (client_id)');
        $this->addSql('ALTER TABLE loans ADD CONSTRAINT FK_82C24DBC19EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE loans DROP CONSTRAINT FK_82C24DBC19EB6921');
        $this->addSql('DROP TABLE clients');
        $this->addSql('DROP TABLE loans');
    }
}
